services:
  redis:
    image: 'redis:alpine'
    container_name: celery-lineage-redis
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    volumes:
      - ./redis_data:/data
    ports:
      - '6379:6379'

  worker:
    image: celery-lineage
    volumes:
      - .:/app
    depends_on:
      - redis
      - scheduler
      - marquez
    env_file:
      - .env
    entrypoint: [ './entrypoint.sh', 'worker', 'default' ]


  scheduler:
    build: .
    image: celery-lineage
    container_name: celery-lineage-scheduler
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - instance=scheduler
    env_file:
      - .env
    entrypoint: ['./entrypoint.sh', 'scheduler']

#  flower:
#    build:
#      context: ./
#      dockerfile: flower/Dockerfile
#    command: ['./entrypoint.sh', 'flower']
#    volumes:
#      - ./flower_data:/db
#      - .:/app
#    depends_on:
#      redis:
#        condition: service_healthy
#      worker:
#        condition: service_started
#    env_file:
#      - .env
#    ports:
#      - '5555:5555'

  marquez:
    image: marquezproject/marquez:0.49.0
    container_name: marquez
    env_file:
      - .env
    environment:
      - PROXY_CHANGE_ORIGIN=true
    depends_on:
      - marquez-db
    links:
      - marquez-db:postgres
    ports:
      - "9000:9000"
      - "9001:9001"
#    volumes:
#      - ./docker/wait-for-it.sh:/usr/src/app/wait-for-it.sh
#    entrypoint: [ "./wait-for-it.sh", "postgres:5432", "--", "./entrypoint.sh" ]

  marquezweb:
    image: marquezproject/marquez-web:0.49.0
    container_name: marquezweb
    env_file:
      - .env
    environment:
      - REACT_APP_ADVANCED_SEARCH=false
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - marquez

  marquez-db:
    image: postgres:14
    container_name: marquez-db
    environment:
      - POSTGRES_USER=marquez
      - POSTGRES_PASSWORD=marquez
      - MARQUEZ_USER=marquez
      - MARQUEZ_PASSWORD=marquez
      - MARQUEZ_DB=marquez
    volumes:
      - marquez-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  marquez-db-data:
